# Generated by Django 3.2.10 on 2022-02-10 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_name', models.CharField(default='default_name', max_length=150, primary_key=True, serialize=False)),
                ('crop_desc', models.CharField(default='default_desc', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('dev_name', models.CharField(default='default_name', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(default='default_name', max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22)),
                ('predicted_class', models.TextField()),
                ('probability', models.DecimalField(decimal_places=16, max_digits=22)),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.crop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.user')),
            ],
        ),
    ]
