# Generated by Django 3.2.10 on 2022-02-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to=models.TextField(blank=True, null=True), verbose_name='IMAGE'),
        ),
        migrations.AddField(
            model_name='data',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
