# Generated by Django 3.2.10 on 2022-02-10 06:40

import APIs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0004_auto_20220210_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to=APIs.models.upload_to, verbose_name='IMAGE'),
        ),
    ]
