# Generated by Django 3.2.10 on 2022-02-10 10:18

import APIs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0008_remove_data_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.TextField()),
                ('startLatitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('startLongitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('endLatitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('endLongitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('predicted_class', models.TextField()),
                ('probability', models.DecimalField(decimal_places=16, max_digits=22)),
                ('frame', models.ImageField(default='images/default.png', upload_to=APIs.models.upload_to, verbose_name='IMAGE')),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.crop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.user')),
            ],
        ),
    ]
