# Generated by Django 3.2.10 on 2022-02-10 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0010_alter_data_predicted_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedClass',
            fields=[
                ('predicted_class', models.CharField(choices=[('northern_leaf_blight', 'northern_leaf_blight'), ('cercospora_gray_leaf_spot', 'cercospora_gray_leaf_spot'), ('common_rust', 'common_rust'), ('healthy', 'healthy'), ('nutrient_deficient', 'nutrient_deficient')], max_length=100, primary_key=True, serialize=False)),
                ('class_desc', models.CharField(default='default_desc', max_length=300)),
                ('crop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.crop')),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='predicted_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.predictedclass'),
        ),
        migrations.AlterField(
            model_name='videoframe',
            name='predicted_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='APIs.predictedclass'),
        ),
    ]
