# Generated by Django 3.2.10 on 2022-02-10 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0011_auto_20220210_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoframe',
            old_name='endLatitude',
            new_name='end_latitude',
        ),
        migrations.RenameField(
            model_name='videoframe',
            old_name='endLongitude',
            new_name='end_longitude',
        ),
        migrations.RenameField(
            model_name='videoframe',
            old_name='startLatitude',
            new_name='start_latitude',
        ),
        migrations.RenameField(
            model_name='videoframe',
            old_name='startLongitude',
            new_name='start_longitude',
        ),
    ]
