# Generated by Django 3.2.10 on 2022-02-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0013_sensor_sensorvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorvalue',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('pressure', 'pressure'), ('luminosity', 'luminosity')], default='temperature', max_length=100),
        ),
    ]
