# Generated by Django 3.2.10 on 2022-04-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0014_sensorvalue_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_name',
            field=models.TextField(blank=True, default='a_maize_11-02-2022_01-33-15.png'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name',
            field=models.CharField(choices=[('maize', 'maize'), ('cotton', 'cotton'), ('rice', 'rice'), ('wheat', 'wheat'), ('jute', 'jute'), ('other', 'other')], max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predictedclass',
            name='predicted_class',
            field=models.CharField(choices=[('northern_leaf_blight', 'northern_leaf_blight'), ('cercospora_gray_leaf_spot', 'cercospora_gray_leaf_spot'), ('common_rust', 'common_rust'), ('healthy', 'healthy'), ('nutrient_deficient', 'nutrient_deficient'), ('disease1', 'disease1'), ('disease2', 'disease2'), ('disease3', 'disease3'), ('disease4', 'disease4'), ('disease5', 'disease5')], max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('pressure', 'pressure'), ('luminosity', 'luminosity'), ('nitrogen', 'nitrogen'), ('phosphorus', 'phosphorus'), ('potassium', 'potassium'), ('pH', 'pH')], default='temperature', max_length=100),
        ),
        migrations.AlterField(
            model_name='sensorvalue',
            name='sensor_type',
            field=models.CharField(choices=[('temperature', 'temperature'), ('humidity', 'humidity'), ('pressure', 'pressure'), ('luminosity', 'luminosity'), ('nitrogen', 'nitrogen'), ('phosphorus', 'phosphorus'), ('potassium', 'potassium'), ('pH', 'pH')], default='temperature', max_length=100),
        ),
    ]
