# Generated by Django 3.2.10 on 2022-03-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0014_sensorvalue_sensor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='file_name',
            field=models.TextField(blank=True, default='a_maize_11-02-2022_01-33-15.png'),
        ),
    ]
