# Generated by Django 3.2.10 on 2022-04-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0017_alter_predictedclass_predicted_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoframe',
            name='file_name',
            field=models.TextField(blank=True, default='a_maize_11-02-2022_01-33-15.png'),
        ),
    ]
